config/routes.rb
Rails.application.routes.draw do

  resources :cover_images, only: [:show], id: /.*?/, format: /[^.]+/

  # health check and version endpoints
  resources :healthcheck, only: [ :index ]
  resources :version, only: [ :index ]

  devise_scope :user do
    get "/users/sign_up", to: redirect('/404')
    post "/users", to: redirect('/404')
    get "/login" => "users/sessions#new"

    # used only to prevent errors in development
    # netbadge will catch this path in prod
    get "/logout", to: "users/sessions#new"
  end
  devise_for :users, controllers: { sessions: 'users/sessions' }

  authenticate :user do
    namespace :admin do
      resources :cover_images do
        member do
          get :reprocess
        end
      end
      require 'sidekiq/web'
      mount Sidekiq::Web => '/workers'
    end
  end

  root to: "admin/cover_images#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cover_image.rb
# Cover Image
class CoverImage < ApplicationRecord
  include Scraper

  has_attached_file :image, styles: {thumb: 'x200^'},
    default_url: '/images/CoverUnavailable.png'

  serialize :response_data, JSON

  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  TYPES = {
    non_music: 'Books, DVDs (not music)',
    music: 'Music'
  }.with_indifferent_access.freeze

  STATUSES = {
    unprocessed: 'Has not been processed',
    error:       'There was a problem retrieving the cover image.',
    not_found:   'Nothing was found after searching',
    processed:   'Successfully processed, image found.'
  }.with_indifferent_access.freeze

  IDENTIFIERS = %w(upc isbn lccn oclc ht_id issn).freeze

  DEFAULT_BOOKS         = %w(Book-Blue.png Book-Gray.png Book-Orange.png).freeze
  DEFAULT_BOOKS_LEN     = DEFAULT_BOOKS.length.freeze
  DEFAULT_MUSIC         = %w(Music-Blue.png Music-Gray.png Music-Orange.png).freeze
  DEFAULT_MUSIC_LEN     = DEFAULT_MUSIC.length.freeze
  DEFAULT_SCHOLARLY     = %w(Scholar-Blue.png Scholar-Gray.png Scholar-Orange.png).freeze
  DEFAULT_SCHOLARLY_LEN = DEFAULT_SCHOLARLY.length.freeze
  DEFAULT_FILM          = %w(Film-Blue.png Film-Gray.png Film-Orange.png).freeze
  DEFAULT_FILM_LEN     = DEFAULT_FILM.length.freeze

  validates :doc_id, presence: true, uniqueness: true

  validates :doc_type, inclusion: {
    in:      TYPES.keys.map(&:to_s),
    message: "Must be either #{TYPES.keys.to_sentence(
      last_word_connector: ' or ',
      two_words_connector: ' or ')}"
  }
  validates :status, inclusion: {in: STATUSES.keys.map(&:to_s)}
  validate :required_identifiers, if: "non_music?"
  validates :artist_name, :album_name, presence: true, if: "music?"

  after_initialize :assign_defaults

  after_commit :lookup, if: ->(ci) {ci.run_lookup}

  before_save :clean_fields

  attr_accessor :run_lookup
  attr_accessor :search_term

  def music?
    doc_type == 'music'
  end

  def non_music?
    doc_type == 'non_music'
  end

  ## returns [Hash] Present id type mapped to value
  #
  def present_ids
    IDENTIFIERS.map do |i|
      ident = self.send(i)
      next unless ident.present?
      [i, ident.strip]
    end.compact.to_h
  end

  # @Returns default image
  def default_image_path
    Rails.root.join('public', 'images', 'CoverUnavailable.png')
  end

  private

  def assign_defaults
    self.status ||= 'unprocessed'
  end

  def clean_fields
    self.artist_name = artist_name.gsub(/\(Musical group\)/i, '').strip if artist_name
  end

  # for non-music validation
  def required_identifiers
    present =
      IDENTIFIERS.any? do |ident|
        self.send(ident).present?
      end
    return if present
    self.errors.add(
      :base, "One of #{IDENTIFIERS.to_sentence(
        last_word_connector: ' or ')} is required.")
  end

end

app/controllers/admin/cover_images_controller.rb
# controller for /admin/cover_images
class Admin::CoverImagesController < ApplicationController

  before_action :authenticate_user!

  before_action :get_cover_image,
    only: [:show, :edit, :update, :reprocess, :destroy]

  def index
    search_term = params.dig(:cover_image, :search_term)
    if search_term.present?
      @cover_images = CoverImage.where(doc_id: search_term)
    else
      @cover_images = CoverImage.all
    end
    @cover_images = @cover_images.order('created_at desc').page(params[:page]).per(20)
  end

  def new
    @cover_image = CoverImage.new
  end

  def create
    @cover_image = CoverImage.new(cover_image_params)
    if @cover_image.image.dirty?
      # Lock the image if it was manually added
      @cover_image.locked = true
      @cover_image.status = CoverImage::STATUSES.keys.last
    end
    if @cover_image.save
      flash[:success] = "Successfully created: #{@cover_image.doc_id}"
      redirect_to action: :index
    else
      render :new
    end
  end

  def edit
  end

  def update
    @cover_image.assign_attributes cover_image_params
    if @cover_image.image.dirty?
      # Lock the image if it was manually added
      @cover_image.locked = true
      @cover_image.status = CoverImage::STATUSES.keys.last
    end
    if @cover_image.save
      @cover_image.lookup
      flash[:success] = "Successfully updated: #{@cover_image.doc_id}"
      redirect_to action: :index
    else
      render action: :edit
    end
  end

  def reprocess
    @cover_image.lookup true

    redirect_to action: params[:redirect]

  end

  def destroy
    if @cover_image.destroy
      flash[:success] = "Successfully deleted: #{@cover_image.doc_id}"
    else
      flash[:alert] = "Could not delete: #{@cover_image.doc_id}"
    end
    redirect_to action: :index
  end

  private

  def cover_image_params
    params.require(:cover_image).permit(
      :doc_type, :doc_id, :status,
      :isbn, :oclc, :lccn, :upc, :ht_id,
      :mbid, :artist_name, :album_name,
      :image
    )
  end


  def get_cover_image
    @cover_image = CoverImage.find(params[:id])
  end

end

app/controllers/cover_images_controller.rb
# Controller for /cover_images
class CoverImagesController < ApplicationController

  ##
  #
  def show
    # params[:id] is the solr id in this case
    cover_image = CoverImage.find_or_initialize_by(
      doc_id: params[:id]
    )


    image_url = URI.join(request.url, cover_image.image.url)

    if cover_image && cover_image.image.present?
      path = cover_image.image.path
    else
      cover_image.assign_attributes cover_image_params.merge(run_lookup: true)
      cover_image.save
      path = cover_image.default_image_path
    end

    status_code = case cover_image.status
    when 'unprocessed'
      # 202
      :accepted
    when 'not_found' || 'error'
      :not_found
    else # processed and found
      :ok
    end

    respond_to do |format|
      format.html do
        send_file path, disposition: 'inline', url_based_filename: true, status: status_code
      end
      format.json do
        uri = generate_image_uri(path)
        render json: {
          image_url: image_url,
          image_base64: uri,
          errors:    cover_image.errors.as_json,
          status: cover_image.status
        },
          status: status_code
      end
    end

  end

  private

  def cover_image_params
    params.permit(
      :doc_type, :title,
      :isbn, :oclc, :lccn, :upc, :mbid, :ht_id, :issn,
      :artist_name, :album_name
    )
  end

  def generate_image_uri(path)
    image = Base64.encode64(File.open(path, &:read))
    "data:image/png;base64,#{image}"
  end

end

app/helpers/admin/cover_images_helper.rb
# Helper for admin/cover_images
module Admin::CoverImagesHelper

  def status_label(status)
    label_name = ''
    case status
      when 'unprocessed'
        label_name = 'label-default'
      when 'error'
        label_name = 'label-danger'
      when 'not_found'
        label_name = 'label-warning'
      when 'processed'
        label_name = 'label-success'
    end
    content_tag 'span', status, class: "label #{label_name}"
  end
end

app/views/admin/cover_images/_form.html.erb
<div class="row">
  <div class="col-sm-6">
    <%= f.input :doc_id, label: "Doc ID", hint: "From Solr", required: true %>
    <%= f.input :doc_type, collection: CoverImage::TYPES.keys, include_blank: false %>
    <%= f.input :title %>
    <p>
    <% if f.object.image.present? %>
      <%= image_tag f.object.image.url(:thumb), class: 'img-responsive' %>
    <%end%>
    </p>
  </div>
  <div class="col-sm-6">
    <%= f.input :image, hint: "leave blank to automatically search" %>
    <%= f.input :locked, label: "&nbsp;&nbsp;Locked Image?", as: :boolean,
      input_html: {data: {toggle: 'toggle'}},
      wrapper_html: {data: {toggle: 'tooltip',
                            placement: "bottom"},
                     title: "Manually adding an image above will lock it in place and remove the ability to reprocess."
    }
    %>
    <%= content_tag :p, f.object.errors[:base].to_sentence,
      class: 'text-danger' if f.object.errors[:base]
    %>
    <%= f.input :isbn %>
    <%= f.input :oclc %>
    <%= f.input :lccn %>
    <%= f.input :upc %>
    <%= f.input :mbid %>
    <%= f.input :artist_name %>
    <%= f.input :album_name %>
  </div>
</div>

app/views/admin/cover_images/destroy.html.erb
<h1>Admin::Images#destroy</h1>
<p>Find me in app/views/admin/images/destroy.html.erb</p>

app/views/admin/cover_images/edit.html.erb
<%= semantic_form_for @cover_image, url: admin_cover_image_path(@cover_image) do |f| %>
<div class="row panel">
  <div class="col-sm-4">
    <h2>Edit Cover Image</h2>
  </div>
  <div class="col-sm-8">
    <p class='text-align-center'>
      <%= f.submit "Save", class: "btn btn-success" %>
      <%= link_to("Reprocess",
                  reprocess_admin_cover_image_path(@cover_image, redirect: :edit),
                  class: "btn btn-warning"
                 ) unless @cover_image.locked
      %>

      <%= link_to "Delete", admin_cover_image_path(@cover_image), method: "DELETE",
        data: {confirm: "Are you sure?"},
        class: "btn btn-danger pull-right"
      %>
    </p>
    <small>
      <%= "Created At: #{short_date @cover_image.created_at}
      | Image updated: #{short_date @cover_image.image_updated_at}" %>
      | Service: <%= @cover_image.service_name %>
      | <%= status_label @cover_image.status %>
    </small>
  </div>
</div>
  <%= render partial: "form", locals: {f: f} %>

  <%= f.submit "Save", class: "btn btn-success" %>

  <hr/>
  <p>
    API Response:
  </p>
  <pre id="response-json" data-response-json="<%=  @cover_image.response_data.to_json %>">
  </pre>

<%end%>

app/views/admin/cover_images/index.html.erb
<div class="row">
  <div class="col-xs-12">
    <%= paginate @cover_images %>
    <table class="table table-striped">
      <thead>
        <tr>
          <th class="col-sm-4">Doc ID</th>
          <th class="col-sm-5">Image</th>
          <th class="col-sm-2">Status</th>
          <th class="col-sm-1">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @cover_images.each do |ci| %>
        <tr>
          <td>
            <%= ci.doc_id %><br/>
            <%= ci.title %>
          </td>
          <td><%= image_tag  ci.image.url(:thumb), class:'img-responsive' %></td>
          <td>
            <%= status_label ci.status %>
            <br/>
            <%= short_date ci.image_updated_at %>
          </td>
          <td>
            <%= link_to "Edit", edit_admin_cover_image_path(ci), class: "btn btn-default" %>
            <br/>
            <% if ci.locked %>
              <span class="label label-primary">Locked</span>
            <%else%>
              <%= link_to "Reprocess",
                reprocess_admin_cover_image_path(ci, redirect: :index),
                class: "btn btn-warning"
              %>
            <%end%>
          </td>
        </tr>
        <%end%>
      </tbody>
    </table>
    <%= paginate @cover_images %>
  </div>
</div>

app/views/admin/cover_images/new.html.erb
<h2>New Cover Image</h2>
<%= semantic_form_for @cover_image, url: admin_cover_images_path do |f| %>
  <%= render partial: "form", locals: {f: f} %>
  <%= f.submit "Create", class: "btn btn-primary btn-lg" %>
<%end%>

app/views/admin/cover_images/show.html.erb
<h1>Admin::Images#show</h1>
<p>Find me in app/views/admin/images/show.html.erb</p>

app/views/admin/cover_images/update.html.erb
<h1>Admin::Images#update</h1>
<p>Find me in app/views/admin/images/update.html.erb</p>