config/routes.rb
Rails.application.routes.draw do

  resources :cover_images, only: [:show], id: /.*?/, format: /[^.]+/

  # health check and version endpoints
  resources :healthcheck, only: [ :index ]
  resources :version, only: [ :index ]

  devise_scope :user do
    get "/users/sign_up", to: redirect('/404')
    post "/users", to: redirect('/404')
    get "/login" => "users/sessions#new"

    # used only to prevent errors in development
    # netbadge will catch this path in prod
    get "/logout", to: "users/sessions#new"
  end
  devise_for :users, controllers: { sessions: 'users/sessions' }

  authenticate :user do
    namespace :admin do
      resources :cover_images do
        member do
          get :reprocess
        end
      end
      require 'sidekiq/web'
      mount Sidekiq::Web => '/workers'
    end
  end

  root to: "admin/cover_images#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/admin/images/index.html.erb
<div class="row">
  <div class="col-xs-12">
    <table class="table table-striped">
      <thead>
      </thead>
      <tbody>
        <% @documents.each do |doc|%>
        <tr>
          <td><%= doc.name %></td>
          <td><%= image_tag  doc.image.url(:thumb) %></td>
          <td><%= link_to "Edit", edit_admin_image_path(doc), class: "btn btn-default" %></td>
        </tr>
        <%end%>
      </tbody>
    </table>
    <%= paginate @documents %>
  </div>
</div>

app/views/admin/images/new.html.erb
<h2>New Cover Photo</h2>
<%= semantic_form_for @document, url: admin_images_path do |f| %>
  <%= render partial: "form", locals: {f: f} %>
  <%= f.submit "Create", class: "btn btn-primary" %>
<%end%>