config/routes.rb
Rails.application.routes.draw do

  resources :cover_images, only: [:show], id: /.*?/, format: /[^.]+/

  # health check and version endpoints
  resources :healthcheck, only: [ :index ]
  resources :version, only: [ :index ]

  devise_scope :user do
    get "/users/sign_up", to: redirect('/404')
    post "/users", to: redirect('/404')
    get "/login" => "users/sessions#new"

    # used only to prevent errors in development
    # netbadge will catch this path in prod
    get "/logout", to: "users/sessions#new"
  end
  devise_for :users, controllers: { sessions: 'users/sessions' }

  authenticate :user do
    namespace :admin do
      resources :cover_images do
        member do
          get :reprocess
        end
      end
      require 'sidekiq/web'
      mount Sidekiq::Web => '/workers'
    end
  end

  root to: "admin/cover_images#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Cover Images</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <%= link_to "Cover Images", root_path, class: "navbar-brand" %>
          </div>

          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
              <li>
                <%= nav_link "New", new_admin_cover_image_path %>
              </li>
              <li>
                <%= nav_link "Workers", admin_sidekiq_web_path %>
              </li>

            </ul>
            <%= form_for :cover_image, method: :get, html: {:class => "navbar-form navbar-left"}  do |f| %>
              <div class=" input-group" style="width:200%">
                <%= f.text_field :search_term, class: "form-control",
                  placeholder: "Search by solr id",
                  value: params.dig( :cover_image, :search_term),
                  label: false %>
                <div class="input-group-btn">
                  <%= f.submit "Search", class: "btn btn-primary"  %>
                </div>
              </div>
            <%end%>
            <ul class="nav navbar-nav navbar-right">
              <li><%= link_to "Sign out", destroy_user_session_path if current_user %></li>
            </ul>
          </div>
        </div>
      </nav>
      <%= flash_messages %>
      <%= yield %>
    </div>
  </body>
</html>